/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#ae3115',
        'primary-container': '#ff6b4a',
        'on-primary': '#ffffff',
        'on-primary-container': '#661000',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#ffb4a3',
        'on-primary-fixed': '#3d0600',
        'on-primary-fixed-variant': '#8c1900',
        'inverse-primary': '#ffb4a3',
        secondary: '#9a433f',
        'secondary-container': '#ff928b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#772926',
        'secondary-fixed': '#ffdad7',
        'secondary-fixed-dim': '#ffb3ae',
        'on-secondary-fixed': '#400104',
        'on-secondary-fixed-variant': '#7c2c29',
        tertiary: '#8a4778',
        'tertiary-container': '#cd82b6',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#561a49',
        'tertiary-fixed': '#ffd7ef',
        'tertiary-fixed-dim': '#feade4',
        'on-tertiary-fixed': '#3a0130',
        'on-tertiary-fixed-variant': '#6e305f',
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#59413c',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#8d716a',
        'outline-variant': '#e1bfb8',
        'surface-tint': '#ae3115',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        'display-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      borderRadius: {
        '4': '4px',
        '8': '8px',
        '12': '12px',
        '16': '16px',
        '20': '20px',
        '24': '24px',
        '28': '28px',
        '32': '32px',
        '40': '40px',
        '48': '48px',
      },
      spacing: {
        'card-gap': '24px',
        'stack-sm': '4px',
        'stack-md': '12px',
        'stack-lg': '24px',
        gutter: '24px',
        'section-padding': '80px',
        'container-max': '1280px',
        base: '8px',
      },
      boxShadow: {
        card: '0 10px 30px rgba(0,0,0,0.04)',
        'card-hover': '0 20px 50px rgba(0,0,0,0.10)',
        nav: '0 10px 30px rgba(0,0,0,0.04)',
        float: '0 20px 50px rgba(255,107,74,0.15)',
        'btn-primary': '0 15px 35px rgba(255,107,74,0.30)',
        'btn-primary-hover': '0 20px 45px rgba(255,107,74,0.40)',
      },
      backdropBlur: {
        xl: '20px',
        '2xl': '40px',
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        blob: 'blob 7s infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { transform: 'translateY(20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
